### ISSUE TITLE
Error poruke u login/registaciji

### ISSUE THREAD

**Issue by DominikRicko** [DominikRicko/Rezijiser#16]
maknuo sam {{errorMessage}} iz HTML-a jer se nije mogla aplikacija kompajlirati, jer nedostaje taj property u komponenti (typescript datoteci), vidjeti što sa time.

**Comment by Folen0909** [comment]
Ja maknio iz componente jer sam mislio da se ne koristi, jer sam stavio svoje svuda, mislio samo da se log-a ništa drugo.
